### ISSUE TITLE
http://freezing-bears.surge.sh/undefined/graphql

### ISSUE THREAD

**Issue by Danjavia** [reindexio/reindex-starter-kit#4]
Hi, the application launch the follwing error when push public dir to surge.

```
bundle.js:77POST http://freezing-bears.surge.sh/undefined/graphql 404 (Not 
```

Can you help me?

I try creating a virtualhost in mi pc, but the same error is launched 

http://reindex.dev/ 

```
fetchWithRetries.js:52 POST http://reindex.dev/undefined/graphql 404 (Not Found)
```

**Comment by fson** [comment]
Hi @Danjavia. It looks like your Reindex URL (`https://<your-app-name>.myreindex.com`) is not passed to the `Reindex` constructor in your code.

By default it's read from `REINDEX_URL` environment variable ([see src/Reindex.js](https://github.com/reindexio/reindex-starter-kit/blob/c1185c0b1250f280c6de89f049c20840adb74f14/src/Reindex.js#L2)). You'll need to set this environment variable when building your app or alternatively edit this file to add your own URL.

Please let me know, if this helps!

**Comment by Danjavia** [comment]
Thanks! run now ;)

**Comment by fson** [comment]
Awesome, let us know if you run into other issues.
