### ISSUE TITLE
Step by Step Install Error .babelrc Error causes build failure

### ISSUE THREAD

**Issue by idkjs** [reindexio/reindex-starter-kit#8]
I included the entire terminal output for contex. I think it has to do with babel trying to refer to my root .babelrc presets settings which I dont have. Why would it refer to the .babelrc in the current working directory? 

Im also this error in the browser:  bundle.js:1 Uncaught SyntaxError: Unexpected token < in at localhost:3000.

Thanks.

This is the error msg:
`ERROR in ./src/index.js
Module build failed: ReferenceError: [BABEL] /Users/klik/projects/reindex-starter-kit-react/src/index.js: Unknown option: /Users/klik/.babelrc.presets`

`Last login: Fri May 20 08:09:38 on ttys000
Alains-MacBook-Pro:reindex-starter-kit-react klik$ reindex login
Reindex URL: Alains-MacBook-Pro:reindex-starter-kit-react klik$ reindex login "https://iso-260.myreindex.com" "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc0FkbWluIjp0cnVlLCJpYXQiOjE0NjM3NDYyMjR9.yyfMov9JNc42lqkQp_6GTVYJ5Mrp-z0c0Q7lF9tjWzc"
You are now logged-in.
Alains-MacBook-Pro:reindex-starter-kit-react klik$ npm install

> fsevents@1.0.12 install /Users/klik/projects/reindex-starter-kit-react/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/klik/projects/reindex-starter-kit-react/node_modules/fsevents/lib/binding/Release/node-v47-darwin-x64/fse.node" is installed via remote
reindex-starter-kit@1.0.0 /Users/klik/projects/reindex-starter-kit-react
├─┬ babel@5.8.38 
│ ├─┬ chokidar@1.5.0 
│ │ ├─┬ anymatch@1.3.0 
│ │ │ ├── arrify@1.0.1 
│ │ │ └─┬ micromatch@2.3.8 
│ │ │   ├─┬ arr-diff@2.0.0 
│ │ │   │ └── arr-flatten@1.0.1 
│ │ │   ├── array-unique@0.2.1 
│ │ │   ├─┬ braces@1.8.4 
│ │ │   │ ├─┬ expand-range@1.8.2 
│ │ │   │ │ └─┬ fill-range@2.2.3 
│ │ │   │ │   ├── is-number@2.1.0 
│ │ │   │ │   ├── isobject@2.1.0 
│ │ │   │ │   └── randomatic@1.1.5 
│ │ │   │ ├── preserve@0.2.0 
│ │ │   │ └── repeat-element@1.1.2 
│ │ │   ├─┬ expand-brackets@0.1.5 
│ │ │   │ └── is-posix-bracket@0.1.1 
│ │ │   ├── extglob@0.3.2 
│ │ │   ├── filename-regex@2.0.0 
│ │ │   ├─┬ kind-of@3.0.3 
│ │ │   │ └── is-buffer@1.1.3 
│ │ │   ├── normalize-path@2.0.1 
│ │ │   ├─┬ object.omit@2.0.0 
│ │ │   │ ├─┬ for-own@0.1.4 
│ │ │   │ │ └── for-in@0.1.5 
│ │ │   │ └── is-extendable@0.1.1 
│ │ │   ├─┬ parse-glob@3.0.4 
│ │ │   │ ├── glob-base@0.3.0 
│ │ │   │ └── is-dotfile@1.0.2 
│ │ │   └─┬ regex-cache@0.4.3 
│ │ │     ├── is-equal-shallow@0.1.3 
│ │ │     └── is-primitive@2.0.0 
│ │ ├── async-each@1.0.0 
│ │ ├─┬ fsevents@1.0.12 
│ │ │ ├── nan@2.3.3 
│ │ │ └─┬ node-pre-gyp@0.6.25
│ │ │   ├─┬ mkdirp@0.5.1 
│ │ │   │ └── minimist@0.0.8 
│ │ │   ├─┬ rc@1.1.6
│ │ │   │ └── minimist@1.2.0 
│ │ │   ├─┬ request@2.69.0
│ │ │   │ ├─┬ form-data@1.0.0-rc4
│ │ │   │ │ └── async@1.5.2 
│ │ │   │ └─┬ har-validator@2.0.6
│ │ │   │   ├─┬ chalk@1.1.3 
│ │ │   │   │ ├── ansi-styles@2.2.1 
│ │ │   │   │ ├── escape-string-regexp@1.0.5 
│ │ │   │   │ ├─┬ has-ansi@2.0.0 
│ │ │   │   │ │ └── ansi-regex@2.0.0 
│ │ │   │   │ ├── strip-ansi@3.0.1 
│ │ │   │   │ └── supports-color@2.0.0 
│ │ │   │   ├─┬ commander@2.9.0 
│ │ │   │   │ └── graceful-readlink@1.0.1 
│ │ │   │   └─┬ is-my-json-valid@2.13.1
│ │ │   │     └── xtend@4.0.1 
│ │ │   ├─┬ rimraf@2.5.2
│ │ │   │ └─┬ glob@7.0.3
│ │ │   │   ├── inherits@2.0.1 
│ │ │   │   ├─┬ minimatch@3.0.0
│ │ │   │   │ └─┬ brace-expansion@1.1.3
│ │ │   │   │   └── concat-map@0.0.1 
│ │ │   │   ├── once@1.3.3 
│ │ │   │   └── path-is-absolute@1.0.0 
│ │ │   ├─┬ tar@2.2.1
│ │ │   │ └── inherits@2.0.1 
│ │ │   └─┬ tar-pack@3.1.3
│ │ │     ├─┬ debug@2.2.0 
│ │ │     │ └── ms@0.7.1 
│ │ │     ├─┬ fstream-ignore@1.0.3
│ │ │     │ └─┬ minimatch@3.0.0
│ │ │     │   └─┬ brace-expansion@1.1.3
│ │ │     │     └── concat-map@0.0.1 
│ │ │     ├── once@1.3.3 
│ │ │     └─┬ readable-stream@2.0.6
│ │ │       ├── core-util-is@1.0.2 
│ │ │       ├── isarray@1.0.0 
│ │ │       ├── string_decoder@0.10.31 
│ │ │       └── util-deprecate@1.0.2 
│ │ ├── glob-parent@2.0.0 
│ │ ├── inherits@2.0.1 
│ │ ├─┬ is-binary-path@1.0.1 
│ │ │ └── binary-extensions@1.4.0 
│ │ ├─┬ is-glob@2.0.1 
│ │ │ └── is-extglob@1.0.0 
│ │ └── readdirp@2.0.0 
│ ├─┬ commander@2.9.0 
│ │ └── graceful-readlink@1.0.1 
│ ├── convert-source-map@1.2.0 
│ ├── fs-readdir-recursive@0.1.2 
│ ├─┬ glob@5.0.15 
│ │ ├─┬ inflight@1.0.5 
│ │ │ └── wrappy@1.0.2 
│ │ └── once@1.3.3 
│ ├── lodash@3.10.1 
│ ├─┬ output-file-sync@1.1.1 
│ │ └── xtend@4.0.1 
│ ├── path-exists@1.0.0 
│ ├── path-is-absolute@1.0.0 
│ ├── slash@1.0.0 
│ └── source-map@0.5.6 
├─┬ babel-core@5.8.38 
│ ├── babel-plugin-constant-folding@1.0.1 
│ ├── babel-plugin-dead-code-elimination@1.0.2 
│ ├── babel-plugin-eval@1.0.1 
│ ├── babel-plugin-inline-environment-variables@1.0.1 
│ ├── babel-plugin-jscript@1.0.4 
│ ├── babel-plugin-member-expression-literals@1.0.1 
│ ├── babel-plugin-property-literals@1.0.1 
│ ├── babel-plugin-proto-to-assign@1.0.4 
│ ├── babel-plugin-react-constant-elements@1.0.3 
│ ├── babel-plugin-react-display-name@1.0.3 
│ ├── babel-plugin-remove-console@1.0.1 
│ ├── babel-plugin-remove-debugger@1.0.1 
│ ├── babel-plugin-runtime@1.0.7 
│ ├─┬ babel-plugin-undeclared-variables-check@1.0.2 
│ │ └── leven@1.0.2 
│ ├── babel-plugin-undefined-to-void@1.1.6 
│ ├── babylon@5.8.38 
│ ├── bluebird@2.10.2 
│ ├─┬ chalk@1.1.3 
│ │ ├── ansi-styles@2.2.1 
│ │ ├── escape-string-regexp@1.0.5 
│ │ ├── has-ansi@2.0.0 
│ │ └── supports-color@2.0.0 
│ ├── core-js@1.2.6 
│ ├─┬ debug@2.2.0 
│ │ └── ms@0.7.1 
│ ├─┬ detect-indent@3.0.1 
│ │ ├── get-stdin@4.0.1 
│ │ └── minimist@1.2.0 
│ ├── esutils@2.0.2 
│ ├── globals@6.4.1 
│ ├─┬ home-or-tmp@1.0.0 
│ │ ├── os-tmpdir@1.0.1 
│ │ └── user-home@1.1.1 
│ ├─┬ is-integer@1.0.6 
│ │ └─┬ is-finite@1.0.1 
│ │   └── number-is-nan@1.0.0 
│ ├── js-tokens@1.0.1 
│ ├── json5@0.4.0 
│ ├─┬ minimatch@2.0.10 
│ │ └─┬ brace-expansion@1.1.4 
│ │   ├── balanced-match@0.4.1 
│ │   └── concat-map@0.0.1 
│ ├── private@0.1.6 
│ ├─┬ regenerator@0.8.40 
│ │ ├─┬ commoner@0.10.4 
│ │ │ ├─┬ detective@4.3.1 
│ │ │ │ └── acorn@1.2.2 
│ │ │ ├── iconv-lite@0.4.13 
│ │ │ └── q@1.4.1 
│ │ ├─┬ defs@1.1.1 
│ │ │ ├─┬ alter@0.2.0 
│ │ │ │ └── stable@0.1.5 
│ │ │ ├── ast-traverse@0.1.1 
│ │ │ ├── breakable@1.0.0 
│ │ │ ├── esprima-fb@15001.1001.0-dev-harmony-fb 
│ │ │ ├── simple-fmt@0.1.0 
│ │ │ ├── simple-is@0.2.0 
│ │ │ ├── stringmap@0.2.2 
│ │ │ ├── stringset@0.2.1 
│ │ │ ├── tryor@0.1.2 
│ │ │ └─┬ yargs@3.27.0 
│ │ │   ├─┬ os-locale@1.4.0 
│ │ │   │ └─┬ lcid@1.0.0 
│ │ │   │   └── invert-kv@1.0.0 
│ │ │   ├── window-size@0.1.4 
│ │ │   └── y18n@3.2.1 
│ │ ├── esprima-fb@15001.1001.0-dev-harmony-fb 
│ │ ├─┬ recast@0.10.33 
│ │ │ ├── ast-types@0.8.12 
│ │ │ ├── esprima-fb@15001.1001.0-dev-harmony-fb 
│ │ │ └── source-map@0.5.6 
│ │ └── through@2.3.8 
│ ├─┬ regexpu@1.3.0 
│ │ ├── esprima@2.7.2 
│ │ ├── regenerate@1.2.1 
│ │ ├── regjsgen@0.2.0 
│ │ └─┬ regjsparser@0.1.5 
│ │   └── jsesc@0.5.0 
│ ├── repeating@1.1.3 
│ ├── resolve@1.1.7 
│ ├── shebang-regex@1.0.0 
│ ├── source-map@0.5.6 
│ ├─┬ source-map-support@0.2.10 
│ │ └─┬ source-map@0.1.32 
│ │   └── amdefine@1.0.0 
│ ├── to-fast-properties@1.0.2 
│ ├── trim-right@1.0.1 
│ └── try-resolve@1.0.1 
├─┬ babel-loader@5.4.0 
│ ├─┬ loader-utils@0.2.15 
│ │ ├── big.js@3.1.3 
│ │ ├── emojis-list@2.0.1 
│ │ ├── json5@0.5.0 
│ │ └── object-assign@4.1.0 
│ └── object-assign@3.0.0 
├─┬ babel-plugin-react-transform@1.1.1 
│ └── path-parse@1.0.5 
├─┬ babel-relay-plugin@0.8.1 
│ └── graphql@0.4.18 
├── babel-runtime@5.8.38 
├─┬ css-loader@0.19.0 
│ ├─┬ css-selector-tokenizer@0.5.4 
│ │ ├── cssesc@0.1.0 
│ │ └── fastparse@1.1.1 
│ ├─┬ cssnano@3.6.2 
│ │ ├─┬ autoprefixer@6.3.6 
│ │ │ ├── browserslist@1.3.1 
│ │ │ ├── caniuse-db@1.0.30000466 
│ │ │ ├── normalize-range@0.1.2 
│ │ │ └── num2fraction@1.2.2 
│ │ ├── decamelize@1.2.0 
│ │ ├── defined@1.0.0 
│ │ ├── indexes-of@1.0.1 
│ │ ├── object-assign@4.1.0 
│ │ ├─┬ postcss-calc@5.2.1 
│ │ │ ├── postcss-message-helpers@2.0.0 
│ │ │ └─┬ reduce-css-calc@1.2.3 
│ │ │   ├── balanced-match@0.1.0 
│ │ │   └─┬ reduce-function-call@1.0.1 
│ │ │     └── balanced-match@0.1.0 
│ │ ├─┬ postcss-colormin@2.2.0 
│ │ │ └─┬ colormin@1.1.0 
│ │ │   ├─┬ color@0.11.1 
│ │ │   │ ├── color-convert@0.5.3 
│ │ │   │ └─┬ color-string@0.3.0 
│ │ │   │   └── color-name@1.1.1 
│ │ │   └── css-color-names@0.0.3 
│ │ ├── postcss-convert-values@2.3.4 
│ │ ├── postcss-discard-comments@2.0.4 
│ │ ├── postcss-discard-duplicates@2.0.1 
│ │ ├── postcss-discard-empty@2.1.0 
│ │ ├── postcss-discard-overridden@0.1.1 
│ │ ├─┬ postcss-discard-unused@2.2.1 
│ │ │ ├── flatten@1.0.2 
│ │ │ └── uniqs@2.0.0 
│ │ ├─┬ postcss-filter-plugins@2.0.0 
│ │ │ └── uniqid@1.0.0 
│ │ ├─┬ postcss-merge-idents@2.1.6 
│ │ │ └── has-own@1.0.0 
│ │ ├── postcss-merge-longhand@2.0.1 
│ │ ├── postcss-merge-rules@2.0.9 
│ │ ├─┬ postcss-minify-font-values@1.0.5 
│ │ │ └── object-assign@4.1.0 
│ │ ├── postcss-minify-gradients@1.0.2 
│ │ ├─┬ postcss-minify-params@1.0.4 
│ │ │ └── alphanum-sort@1.0.2 
│ │ ├─┬ postcss-minify-selectors@2.0.5 
│ │ │ └─┬ postcss-selector-parser@2.0.0 
│ │ │   └── uniq@1.0.1 
│ │ ├── postcss-normalize-charset@1.1.0 
│ │ ├─┬ postcss-normalize-url@3.0.7 
│ │ │ ├── is-absolute-url@2.0.0 
│ │ │ └─┬ normalize-url@1.5.2 
│ │ │   ├── object-assign@4.1.0 
│ │ │   ├── prepend-http@1.0.4 
│ │ │   ├─┬ query-string@4.1.0 
│ │ │   │ └── strict-uri-encode@1.1.0 
│ │ │   └─┬ sort-keys@1.1.2 
│ │ │     └── is-plain-obj@1.1.0 
│ │ ├── postcss-ordered-values@2.2.1 
│ │ ├── postcss-reduce-idents@2.3.0 
│ │ ├── postcss-reduce-transforms@1.0.3 
│ │ ├─┬ postcss-svgo@2.1.3 
│ │ │ ├─┬ is-svg@2.0.1 
│ │ │ │ └── html-comment-regex@1.1.0 
│ │ │ └─┬ svgo@0.6.6 
│ │ │   ├── coa@1.0.1 
│ │ │   ├── colors@1.1.2 
│ │ │   ├─┬ csso@2.0.0 
│ │ │   │ ├── clap@1.1.1 
│ │ │   │ └── source-map@0.5.6 
│ │ │   ├─┬ js-yaml@3.6.1 
│ │ │   │ ├─┬ argparse@1.0.7 
│ │ │   │ │ └── sprintf-js@1.0.3 
│ │ │   │ └── esprima@2.7.2 
│ │ │   ├── sax@1.2.1 
│ │ │   └── whet.extend@0.9.9 
│ │ ├── postcss-unique-selectors@2.0.2 
│ │ ├── postcss-value-parser@3.3.0 
│ │ └── postcss-zindex@2.1.1 
│ ├─┬ postcss@5.0.21 
│ │ ├── js-base64@2.1.9 
│ │ ├── source-map@0.5.6 
│ │ └── supports-color@3.1.2 
│ ├── postcss-modules-extract-imports@1.0.0-beta2 
│ ├── postcss-modules-local-by-default@1.0.0-beta1 
│ ├── postcss-modules-scope@1.0.0-beta2 
│ └── source-list-map@0.1.6 
├─┬ express@4.13.4 
│ ├─┬ accepts@1.2.13 
│ │ ├─┬ mime-types@2.1.11 
│ │ │ └── mime-db@1.23.0 
│ │ └── negotiator@0.5.3 
│ ├── array-flatten@1.1.1 
│ ├── content-disposition@0.5.1 
│ ├── content-type@1.0.2 
│ ├── cookie@0.1.5 
│ ├── cookie-signature@1.0.6 
│ ├── depd@1.1.0 
│ ├── escape-html@1.0.3 
│ ├── etag@1.7.0 
│ ├─┬ finalhandler@0.4.1 
│ │ └── unpipe@1.0.0 
│ ├── fresh@0.3.0 
│ ├── merge-descriptors@1.0.1 
│ ├── methods@1.1.2 
│ ├─┬ on-finished@2.3.0 
│ │ └── ee-first@1.1.1 
│ ├── parseurl@1.3.1 
│ ├── path-to-regexp@0.1.7 
│ ├─┬ proxy-addr@1.0.10 
│ │ ├── forwarded@0.1.0 
│ │ └── ipaddr.js@1.0.5 
│ ├── qs@4.0.0 
│ ├── range-parser@1.0.3 
│ ├─┬ send@0.13.1 
│ │ ├── destroy@1.0.4 
│ │ ├── http-errors@1.3.1 
│ │ └── statuses@1.2.1 
│ ├── serve-static@1.10.2 
│ ├─┬ type-is@1.6.13 
│ │ └── media-typer@0.3.0 
│ ├── utils-merge@1.0.0 
│ └── vary@1.0.1 
├─┬ react@0.14.8 
│ ├─┬ envify@3.4.0 
│ │ └─┬ jstransform@10.1.0 
│ │   ├── base62@0.1.1 
│ │   ├── esprima-fb@13001.1001.0-dev-harmony-fb 
│ │   └── source-map@0.1.31 
│ └─┬ fbjs@0.6.1 
│   ├─┬ loose-envify@1.2.0 
│   │ └── js-tokens@1.0.3 
│   ├─┬ promise@7.1.1 
│   │ └── asap@2.0.3 
│   ├── ua-parser-js@0.7.10 
│   └── whatwg-fetch@0.9.0 
├── react-dom@0.14.8 
├─┬ react-relay@0.8.1 
│ ├── babel-runtime@5.8.24 
│ ├── fbjs@0.8.2 
│ └── react-static-container@1.0.1 
├── react-transform-catch-errors@1.0.2 
├─┬ react-transform-hmr@1.0.4 
│ ├─┬ global@4.3.0 
│ │ ├─┬ min-document@2.18.0 
│ │ │ └── dom-walk@0.1.1 
│ │ └── process@0.5.2 
│ └─┬ react-proxy@1.1.8 
│   ├── lodash@4.12.0 
│   └── react-deep-force-update@1.0.1 
├─┬ redbox-react@1.2.5 
│ ├─┬ error-stack-parser@1.3.6 
│ │ └── stackframe@0.3.1 
│ └── object-assign@4.1.0 
├─┬ reindex-js@0.3.1 
│ ├── fbemitter@2.0.2 
│ ├── fbjs@0.1.0-alpha.7 
│ ├── invariant@2.2.1 
│ ├─┬ isomorphic-fetch@2.2.1 
│ │ ├─┬ node-fetch@1.5.2 
│ │ │ ├── encoding@0.1.12 
│ │ │ └── is-stream@1.1.0 
│ │ └── whatwg-fetch@1.0.0 
│ └── winchan@0.1.2 
├── style-loader@0.12.4 
├─┬ webpack@1.13.1 
│ ├── acorn@3.1.0 
│ ├── async@1.5.2 
│ ├── clone@1.0.2 
│ ├─┬ enhanced-resolve@0.9.1 
│ │ ├── graceful-fs@4.1.4 
│ │ └── memory-fs@0.2.0 
│ ├── interpret@0.6.6 
│ ├─┬ memory-fs@0.3.0 
│ │ ├─┬ errno@0.1.4 
│ │ │ └── prr@0.0.0 
│ │ └─┬ readable-stream@2.1.4 
│ │   ├── buffer-shims@1.0.0 
│ │   ├── core-util-is@1.0.2 
│ │   ├── isarray@1.0.0 
│ │   ├── process-nextick-args@1.0.7 
│ │   └── util-deprecate@1.0.2 
│ ├─┬ mkdirp@0.5.1 
│ │ └── minimist@0.0.8 
│ ├─┬ node-libs-browser@0.5.3 
│ │ ├── assert@1.4.0 
│ │ ├─┬ browserify-zlib@0.1.4 
│ │ │ └── pako@0.2.8 
│ │ ├─┬ buffer@3.6.0 
│ │ │ ├── base64-js@0.0.8 
│ │ │ └── ieee754@1.1.6 
│ │ ├─┬ console-browserify@1.1.0 
│ │ │ └── date-now@0.1.4 
│ │ ├── constants-browserify@0.0.1 
│ │ ├─┬ crypto-browserify@3.2.8 
│ │ │ ├── pbkdf2-compat@2.0.1 
│ │ │ ├── ripemd160@0.2.0 
│ │ │ └── sha.js@2.2.6 
│ │ ├── domain-browser@1.1.7 
│ │ ├── events@1.1.0 
│ │ ├─┬ http-browserify@1.7.0 
│ │ │ └── Base64@0.2.1 
│ │ ├── https-browserify@0.0.0 
│ │ ├── os-browserify@0.1.2 
│ │ ├── path-browserify@0.0.0 
│ │ ├── process@0.11.3 
│ │ ├── punycode@1.4.1 
│ │ ├── querystring-es3@0.2.1 
│ │ ├─┬ readable-stream@1.1.14 
│ │ │ └── isarray@0.0.1 
│ │ ├─┬ stream-browserify@1.0.0 
│ │ │ └─┬ readable-stream@1.1.14 
│ │ │   └── isarray@0.0.1 
│ │ ├── string_decoder@0.10.31 
│ │ ├─┬ timers-browserify@1.4.2 
│ │ │ └── process@0.11.3 
│ │ ├── tty-browserify@0.0.0 
│ │ ├─┬ url@0.10.3 
│ │ │ └── punycode@1.3.2 
│ │ ├── util@0.10.3 
│ │ └─┬ vm-browserify@0.0.4 
│ │   └── indexof@0.0.1 
│ ├─┬ optimist@0.6.1 
│ │ ├── minimist@0.0.10 
│ │ └── wordwrap@0.0.2 
│ ├─┬ supports-color@3.1.2 
│ │ └── has-flag@1.0.0 
│ ├── tapable@0.1.10 
│ ├─┬ uglify-js@2.6.2 
│ │ ├── async@0.2.10 
│ │ ├── source-map@0.5.6 
│ │ ├── uglify-to-browserify@1.0.2 
│ │ └─┬ yargs@3.10.0 
│ │   ├── camelcase@1.2.1 
│ │   ├─┬ cliui@2.1.0 
│ │   │ ├─┬ center-align@0.1.3 
│ │   │ │ ├─┬ align-text@0.1.4 
│ │   │ │ │ ├── longest@1.0.1 
│ │   │ │ │ └── repeat-string@1.5.4 
│ │   │ │ └── lazy-cache@1.0.4 
│ │   │ └── right-align@0.1.3 
│ │   └── window-size@0.1.0 
│ ├─┬ watchpack@0.2.9 
│ │ └── async@0.9.2 
│ └─┬ webpack-core@0.6.8 
│   └── source-map@0.4.4 
├─┬ webpack-dev-middleware@1.6.1 
│ └── mime@1.3.4 
└─┬ webpack-hot-middleware@2.10.0 
  ├── ansi-html@0.0.5 
  ├── html-entities@1.2.0 
  ├── querystring@0.2.0 
  └─┬ strip-ansi@3.0.1 
    └── ansi-regex@2.0.0 

Alains-MacBook-Pro:reindex-starter-kit-react klik$ reindex schema-fetch
Fetching Reindex schema from https://isomeric-krypton-260.myreindex.com...
Writing to ./ReindexSchema.json...
Done!
Alains-MacBook-Pro:reindex-starter-kit-react klik$ reindex schema-relay ./data/schema.json
Fetching Relay schema from https://isomeric-krypton-260.myreindex.com...
Writing to ./data/schema.json...
Done!
Alains-MacBook-Pro:reindex-starter-kit-react klik$ npm start

> reindex-starter-kit@1.0.0 start /Users/klik/projects/reindex-starter-kit-react
> node devServer.js

Listening at http://localhost:3000
webpack built 0c31ff3a8e31e15d56c5 in 1143ms
Hash: 0c31ff3a8e31e15d56c5
Version: webpack 1.13.1
Time: 1143ms
    Asset     Size  Chunks       Chunk Names
bundle.js  99.7 kB       0       main
chunk    {0} bundle.js (main) 73.1 kB [rendered]
    [0] multi main 40 bytes {0} [built] [1 error]
    [1](webpack)-hot-middleware/client.js 4.18 kB {0} [built]
    [2](webpack)/buildin/module.js 251 bytes {0} [built]
    [3] ./~/strip-ansi/index.js 161 bytes {0} [built]
    [4] ./~/ansi-regex/index.js 135 bytes {0} [built]
    [5](webpack)-hot-middleware/client-overlay.js 1.73 kB {0} [built]
    [6] ./~/ansi-html/index.js 4.02 kB {0} [built]
    [7] ./~/html-entities/index.js 231 bytes {0} [built]
    [8] ./~/html-entities/lib/xml-entities.js 2.98 kB {0} [built]
    [9] ./~/html-entities/lib/html4-entities.js 6.57 kB {0} [built]
   [10] ./~/html-entities/lib/html5-entities.js 49 kB {0} [built]
   [11](webpack)-hot-middleware/process-update.js 3.88 kB {0} [built]

ERROR in ./src/index.js
Module build failed: ReferenceError: [BABEL] /Users/klik/projects/reindex-starter-kit-react/src/index.js: Unknown option: /Users/klik/.babelrc.presets
    at Logger.error (/Users/klik/projects/reindex-starter-kit-react/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/Users/klik/projects/reindex-starter-kit-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/Users/klik/projects/reindex-starter-kit-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/Users/klik/projects/reindex-starter-kit-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/Users/klik/projects/reindex-starter-kit-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/Users/klik/projects/reindex-starter-kit-react/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/Users/klik/projects/reindex-starter-kit-react/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/Users/klik/projects/reindex-starter-kit-react/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/Users/klik/projects/reindex-starter-kit-react/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/Users/klik/projects/reindex-starter-kit-react/node_modules/babel-loader/index.js:71:12)
 @ multi main`

**Comment by freiksenet** [comment]
Thank you for you report!

This is very weird, I've just tried cloning and installing from scratch and it worked fine.

Can you try https://github.com/reindexio/reindex-starter-kit-react-auth0? I just want to find out if some other project with similar setup will build, so that we can figure out if the problem is with the starter-kit or somewhere else.
